### ISSUE TITLE
Don't use GitHub as a CDN

### ISSUE THREAD

**Issue by andrewbranch** [axemclion/IndexedDBShim#109]
[Here's why.](http://stackoverflow.com/questions/5502540/should-github-be-used-as-a-cdn-for-javascript-libraries) Easy fix: change the Readme.

**Comment by axemclion** [comment]
@andrewbranch, can you send int a pull request please ?

**Comment by andrewbranch** [comment]
Only because I do so love pumping up that “Repositories You Contribute To” number :)

**Comment by axemclion** [comment]
:)

Well, you found it, and this would be the best way to credit you !!

**Comment by telno** [comment]
@axemclion - can you merge the incoming-pr branch with master branch?  This fix to the readme file is pretty important.  I spent a good amount of time debugging a problem which was already resolved, but regressed in the cached version of the file being returned from http://axemclion.github.com/IndexedDBShim/dist/IndexedDBShim.js

**Comment by DickvdBrink** [comment]
Merged, thanks for the PR!
