### ISSUE TITLE
qUnit tests failing in Opera and Safari

### ISSUE THREAD

**Issue by jessecravens** [axemclion/IndexedDBShim#12]
In Opera 12 build 1467, I get a global failure (1,0,1)

Uncaught exception: SyntaxError: Function constructor: failed to compile functionSource:    http://nparashuram.com/IndexedDBShim/src/util.js:24

And in Safari, Version 5.1.7 (7534.57.2) - I get an intermittent issues with test 21,24,25 failing:
1. Indexes: Adding data after index is created (1, 0, 1)Rerun
   Could not add data
2. Indexes: Index Get (1, 0, 1)Rerun
   Got object from Index Get
   Expected:  
   {
   "Boolean": true,
   "Float": 0.5313656725920737,
   "Int": 18,
   "String": "Sample Tue Jul 17 2012 15:53:20 GMT-0500 (CDT)"
   }
   Result: 
   undefined
   Diff:  
   {
   "Boolean": true,
   "Float": 0.5313656725920737,
   "Int": 18,
   "String": "Sample Tue Jul 17 2012 15:53:20 GMT-0500 (CDT)"
   } undefined 
3. Indexes: Index Get Key (1, 0, 1)Rerun
   Got key from Index Get
   Expected:  
   11
   Result: 
   undefined
   Diff:  
   11 undefined 

are you aware of these issues?

**Comment by axemclion** [comment]
The issues 21, 24, and 25 are due to the way the tests are written. They occur as some indexes have more than 2 records matching, and I check only against one. 

Will edit the test case.

**Comment by axemclion** [comment]
Fixed this in SHA: ccd64befcdc686ccc1867d40c582136518022caf
