### ISSUE TITLE
MIT dual-license

### ISSUE THREAD

**Issue by philthomas-tg** [axemclion/IndexedDBShim#133]
Hi,  

Thanks for the shim - it works great.  Would it be possible to have this dual-licensed under MIT license?

Thanks!

**Comment by axemclion** [comment]
I think dual license should not be a problem. Asking @DickvdBrink as he is the co-owner of the project.

**Comment by DickvdBrink** [comment]
I will look into it this week or next week!
I don't know much about licensing so I'm not sure if it is allowed to have the Apache license and MIT.

**Comment by DickvdBrink** [comment]
Sorry for not getting this done this week. Did some searching and I think it is possible. Other open source projects seem to just add the additional license file to source control and be done with it ;p 
I've done this locally, just need to figure some things out before I push :)

**Comment by philthomas-tg** [comment]
Hi Dick,

Thanks for looking into this. Yes, I think other projects just add both licenses without it being an issue.

Thanks,
Phil

**Comment by DickvdBrink** [comment]
I've added the MIT License file. Should be oke :)

**Comment by axemclion** [comment]
@DickvdBrink Thanks for fixing this issue.

**Comment by philthomas-tg** [comment]
Thanks guys!
