### ISSUE TITLE
opening IDBCursor with IDBKeyRange.only(0) returns all records in objectstore

### ISSUE THREAD

**Issue by jaeholop** [axemclion/IndexedDBShim#134]
IDBCursor.prototype.__find checks for the existence of lower and upper bound with:

```
(me.__range.lower || me.__range.upper)
```

If me.__range.lower = me.__range.upper = 0, then (me.__range.lower || me.__range.upper) returns false.

I was able to mitigate this issue by comparing the lower and upper values to -1.
i.e. (me.__range.lower || me.__range.upper) becomes 

```
(me.__range.lower > -1 || me.__range.upper > -1)
```

if (me.__range.lower) becomes

```
if (me.__range.lower > -1)
```

and if (me.__range.upper) becomes

```
if (me.__range.upper > -1)
```

**Comment by mattjacobsen** [comment]
I've created a pull request that should solve this for you (#158)

**Comment by DickvdBrink** [comment]
@mattjacobsen,this one is fixed right?

**Comment by mattjacobsen** [comment]
yep this one's fixed
