### ISSUE TITLE
Records with key of 0 cannot be updated with in-line keys

### ISSUE THREAD

**Issue by adam-marshall** [axemclion/IndexedDBShim#142]
In the code, when checking to see if a key already exists on an object value to be saved, the check is:

`if (!primaryKey) {`

line 1044 in the distributed code, within IDBObjectStore.prototype.__deriveKey.

However if the key is 0, this will not update, it will insert a new record with a new auto-generated ID. Perhaps it should be:

`if (primaryKey === undefined) {`

**Comment by axemclion** [comment]
@adam-marshall Can you send a pull request for this please ?

**Comment by adam-marshall** [comment]
Just did but I'm not sure if it worked ok. Let me know if not...

**Comment by DickvdBrink** [comment]
Thanks for the PR #143!
