### ISSUE TITLE
Missing incoming-pr branch

### ISSUE THREAD

**Issue by sdemjanenko** [axemclion/IndexedDBShim#147]
The `Contributing.md` file says to submit pull requests to the branch `incoming-pr`.  Unfortunately it is missing from this repo.

**Comment by axemclion** [comment]
Yes, the incoming=pr branch was a bad idea :( I had created that to protect the Sauce credentials, but it turned out to be a pain for most people as they sent PRs to master anyway. Please send in your PR to master. 

The contributing.md also needs to be updated.

**Comment by DickvdBrink** [comment]
contributing.md is updated. Thanks
