### ISSUE TITLE
Range Filtering on Indexes

### ISSUE THREAD

**Issue by pixelcort** [axemclion/IndexedDBShim#15]
Steps to reproduce:
1. Go to http://nparashuram.com/jquery-indexeddb/example/ in Safari, which will use the shim
2. Enter `X=[];$.indexedDB("MyECommerceSite").objectStore("catalog").index("price").each(function(){X.push(arguments);}, [150])` into the console
3. Go to the same page in Chrome, which will use the native IndexedDB implementation
4. Enter the same code snippet into the console in Chrome.

Expected the length of X in both browsers to be the same. With the shim, Safari shows 0 and without the shim, Chrome shows 2.

**Comment by axemclion** [comment]
Fixed in SHA: ed0d0fe4e9f12e56148ba2941a04fc309f0c5afc
