### ISSUE TITLE
Number of tests run is inconsistent in Chrome

### ISSUE THREAD

**Issue by pixelcort** [axemclion/IndexedDBShim#21]
In Chrome 21.0.1180.77, the number of tests run varies each time:
1. Go to http://nparashuram.com/IndexedDBShim/test/index.html in Chrome
2. Reload the page over and over again

Expect the number of tests run to remain the same each time.

Got different number of tests run each time, from 123 to 134. (In some cases it would say 0 tests, too.)

**Comment by pixelcort** [comment]
Safari also sometimes has different numbers of tests run.

**Comment by axemclion** [comment]
Fixed this, looks like the problem was with get Index - having duplicate value for Indexes. Fixed this. Please verify.

**Comment by pixelcort** [comment]
Nope, still runs different numbers of tests each time. Did http://nparashuram.com/IndexedDBShim/test/index.html get updated?

**Comment by axemclion** [comment]
I updated the index tests only - you should see 25 tests running in total - 

![Screenshot](http://i46.tinypic.com/282gg1k.png)

**Comment by pixelcort** [comment]
The number of test groups remains consistent at 25, but the number of test that run seems to vary each time.

![number varies](http://f.cl.ly/items/392M0p0l2j1x30082Q1y/Screen%20Shot%202012-11-03%20at%201.14.25%20PM.png)

**Comment by axemclion** [comment]
Was due to the way Index and cursor tests were written. Fixed this in c155ec7d597c28549ac5fdaee5883b6b9ec5bfa5

**Comment by pixelcort** [comment]
On Chrome 22.0.1229.94 (OS X 10.8.2), http://nparashuram.com/IndexedDBShim/test/index.html still results in different numbers of tests being run each time. Sometimes it's as low as 96, other times it's as high as 99.
