### ISSUE TITLE
Fails in Safari, Android, iPad...

### ISSUE THREAD

**Issue by iandevlin** [axemclion/IndexedDBShim#26]
The library fails in Safari, on Android (2.2) and on the (first gen) iPad when used with db.js.

The test.html page that you provide, works fine, but I noticed that this is standalone, so I assume the issue is with db.js.

I know that these browsers don't support IndexedDB but I thought that the whole point of this plugin was to mask over the fact that IndexedDB isn't supported and to use webSql instead?

If certain combinations between libs etc. are not supported, then you should mention that.

**Comment by axemclion** [comment]
Are there any test cases that I could look at, to investigate the failure ?

**Comment by axemclion** [comment]
Spoke on Twitter, and looks like the tests were passing. Closing this issue as this is not an issue with the IndexedDB Shim itself.
