### ISSUE TITLE
Polyfill fails in Android browser

### ISSUE THREAD

**Issue by MrBigDog2U** [axemclion/IndexedDBShim#37]
The Android browser (not Chrome but the "Internet" or "Browser" app) does not allow window.indexedDB to be overwritten. Any assignment to window.indexedDB is ignored and the previous value is left in place. Unfortunately, IndexedDBShim operates by overwriting the value in the window.indexedDB property.

Has anyone come up with a workaround for this issue? The only thing I can think of is to make all of the components that use the polyfill aware of its existence which sort of defeats the purpose.

I am doing this testing on a Samsung Galaxy SIII running 4.1.1. I suspect that earlier Droid browser versions will also exhibit this behavior.

**Comment by Raynos** [comment]
Try `Object.defineProperty(window, "indexedDB", { ... })`

**Comment by MrBigDog2U** [comment]
That works. Thanks Raynos. I suggest that the polyfill be changed to use this mechanism instead of the window.indexedDB = ... approach.

The reason that I need this is that, on the Android browser, the base implementation of indexedDB does not provide support for deleteDatabase. In instances where the full IndexedDB API is not supported, it seems like it would be beneficial to use the polyfill to provide full API support if possible.

According to http://caniuse.com/sql-storage, the Android browser provides support for WebSQL all the way back to version 2.1. According to http://caniuse.com/indexeddb, it isn't supposed to provide any support at all for IndexedDB. However (at least on the GSIII), it provides a partial implementation - not complete support, just enough to make the polyfill think that it's supported.

My thought is to have IndexedDBShim make the following checks
- if any of the standard indexedDB objects provide full support, use it.
- else, if WebSQL can be used, use the polyfill.
- else, use whatever object gives the best behavior.

Any thoughts or feedback?

**Comment by DickvdBrink** [comment]
This does now work as expected. 
See code: https://github.com/axemclion/IndexedDBShim/blob/df18dd71eb4b9b53c3fc82c3bbbde1c28d681f18/dist/IndexedDBShim.js#L1687
This is done for everything below Android 4.3 (except for Chrome on Android)
