### ISSUE TITLE
index is created but objectStore.indexNames gets lost

### ISSUE THREAD

**Issue by mvayngrib** [axemclion/IndexedDBShim#42]
I'm running IndexTests.js in Chrome 23.0. Please see the attached image. "index" is non-null and the cursor opens just fine, but objectStore.indexNames is empty.

Thank you very much for the shim btw!

![objectStore-indexNames](https://f.cloud.github.com/assets/83948/90241/4d19ee48-656e-11e2-8f96-3f1210d994f8.png)

**Comment by DickvdBrink** [comment]
Hope to work on it soon, sorry for taking so long :)

**Comment by DickvdBrink** [comment]
Fixed with #164, thanks for reporting!
