### ISSUE TITLE
iPad Issues

### ISSUE THREAD

**Issue by nevf** [axemclion/IndexedDBShim#5]
Parashuram, this a great idea, thanks for your efforts. I've run the tests and trial on Chrome on Win 7 and they all run fine.

However both fail on my iPad (1). There are various errors including SyntaxError: Init.js:11, ReferenceError: Can't find variable: logger. etc. On the iPad I get 23 tests of 80 passed. If I can provide more info just let me know.

-Neville

**Comment by axemclion** [comment]
Was a syntax error in the way the files were built, corrected in SHA: cd49a0cf408c7fffb63d964bc468c41ec7fe3064

**Comment by nevf** [comment]
@axemclion It took a couple of refreshes on my iPad but all tests are passing now. Great job.

**Comment by axemclion** [comment]
Glad that it works !! The refreshes were probably due to the caches.
