### ISSUE TITLE
util.js/StringList does not match the behaviour of DOMStringList in any modern browser.

### ISSUE THREAD

**Issue by Psithief** [axemclion/IndexedDBShim#50]
The numeric indices should be properties of the object. Both Firefox and WebKit browsers allow access to the properties with a for-length construct.

``` javascript
for(var i = 0;i<list.length;i++)
  console.log(list[i])
```

StringList needs to replicate this behaviour because it is how everyone expects it to work.

> http://www.w3.org/TR/DOM-Level-3-Core/core.html#DOMStringList
> **Attributes**
> **length of type unsigned long, readonly**
> The number of DOMStrings in the list. The range of valid child node indices is 0 to length-1 inclusive.

.length is an attribute but not the only property, each child node should also be accessible as a property.

**Comment by mikaelletang** [comment]
As a side note, this prevent the shim to work with db.js: 
db.js tries to iterate through db.objectStoreNames to assign each dataStore as a property of the db object, and this iteration fails because db.objectStoreNames[i] returns  undefined.

**Comment by axemclion** [comment]
Would appreciate a pull request for this. :)

**Comment by gabrielmaldi** [comment]
This breaks Android's 2.3 stock Browser, see: https://github.com/axemclion/IndexedDBShim/issues/73
