### ISSUE TITLE
Test #21 Indexes: Creating Indexes fails in Chrome 25.0.1364.172 on Windows 7

### ISSUE THREAD

**Issue by CoolEsh** [axemclion/IndexedDBShim#55]
Please take a look on attached screenshot.
![tests_failed](https://f.cloud.github.com/assets/2290212/301915/180c5e26-95f1-11e2-96e9-c87c2e2aa540.jpg)

**Comment by axemclion** [comment]
Does not seem to fail anymore. Closing issue as no repro. Please reopen if you still have problems.
