### ISSUE TITLE
Phantom.js support for testing

### ISSUE THREAD

**Issue by tanx** [axemclion/IndexedDBShim#60]
Hey there,

great work with the shim! I just migrated over to this from lawnchair.js.

One thing I'm missing though with this library is automating my qunit tests via grunt/phantomjs. Since phantomjs supports websql it should work (at least it used to with lawnchair). But I haven't got it to work with the idb shim yet.

Here's the corresponding bug on phantom.js:
https://github.com/ariya/phantomjs/issues/10992

Any thought? Thanks

**Comment by DickvdBrink** [comment]
We are running the test with phantoms now, so it  should work.
See the code for an example. If you have any questions, feel free to ask!
