### ISSUE TITLE
Had to use grunt --force. Expected results?

### ISSUE THREAD

**Issue by notbrain** [axemclion/IndexedDBShim#63]
Just upgraded node 0.10.10 and npm 1.2.25 to latest on OSX 10.8.3. Finally got grunt installed after much effort, then installed all the contrib-\* modules, then ran it. Had to use --force to get the concat to run. Just curious if this is the usual level of ridiculousness involved. Maybe it's late and I should go home. I shouldn't want this installed anyway, right? 

Doh! All I wanted was a non-minified dev version. Looks like the link on the home page links to the minified production version twice. Sigh.

```
: grunt --force
Running "jshint:files" (jshint) task
Linting src/Init.js...ERROR
[L4:C5] W079: Redefinition of 'idbModules'.
var idbModules = {};
Linting test/DatabaseTests.js...ERROR
[L8:C9] W020: Read only.
    dbVersion = dbOpenRequest.result.version || 0;
Linting test/sampleData.js...ERROR
[L1:C5] W079: Redefinition of 'DB'.
var DB = {
Linting test/sampleData.js...ERROR
[L12:C5] W079: Redefinition of 'sample'.
var sample = (function(){

Warning: Task "jshint:files" failed. Used --force, continuing.

Running "concat:dist" (concat) task
File "dist/IndexedDBShim.js" created.

Running "uglify:all" (uglify) task
Source Map "dist/IndexedDBShim.min.map" created.
File "dist/IndexedDBShim.min.js" created.

Done, but with warnings.
```

**Comment by axemclion** [comment]
You are right, looks like the jshint is failing. Will fix this right away.

**Comment by axemclion** [comment]
Just checked and you dont have to run grunt --force. Ideally, you just have to run npm install and then grunt. That should give your the required output.

**Comment by axemclion** [comment]
Can you please reopen if you still get those bugs ?

**Comment by notbrain** [comment]
Still get this after doing `npm install grunt; npm install -g grunt-cli` with a new git clone.

```
: grunt
>> Local Npm module "grunt-contrib-concat" not found. Is it installed?
>> Local Npm module "grunt-contrib-uglify" not found. Is it installed?
>> Local Npm module "grunt-contrib-connect" not found. Is it installed?
>> Local Npm module "grunt-saucelabs" not found. Is it installed?
>> Local Npm module "grunt-contrib-jshint" not found. Is it installed?
>> Local Npm module "grunt-contrib-watch" not found. Is it installed?
Warning: Task "jshint" not found. Use --force to continue.

Aborted due to warnings.
```

**Comment by notbrain** [comment]
Followed up with `npm install grunt-contrib-concat grunt-contrib-uglify grunt-contrib-connect` `grunt-saucelabs grunt-contrib-jshint grunt-contrib-watch` to get those, now I'm back where I started (I'm at home on a different machine same versions of everything).

```
 : grunt
Running "jshint:files" (jshint) task
Linting src/Init.js...ERROR
[L4:C5] W079: Redefinition of 'idbModules'.
var idbModules = {};
Linting test/DatabaseTests.js...ERROR
[L8:C9] W020: Read only.
    dbVersion = dbOpenRequest.result.version || 0;
Linting test/sampleData.js...ERROR
[L1:C5] W079: Redefinition of 'DB'.
var DB = {
Linting test/sampleData.js...ERROR
[L12:C5] W079: Redefinition of 'sample'.
var sample = (function(){

Warning: Task "jshint:files" failed. Use --force to continue.

Aborted due to warnings.
```

**Comment by notbrain** [comment]
`npm install grunt` has these warnings (should this be filed on their bug list?) (also get the same warns when I install grunt-cli)

```
npm WARN package.json dateformat@1.0.2-1.2.3 No repository field.
...
npm WARN package.json eventemitter2@0.4.11 No repository field.
npm WARN package.json eventemitter2@0.4.11 'repositories' (plural) Not supported.
npm WARN package.json Please pick one as the 'repository' field
```

**Comment by darhamid** [comment]
I had a similar problem. I then used the below command and it worked for me

grunt server

**Comment by g2jakhmola** [comment]
I am facing the same problem when i hit command grunt server

grunt-open/node_modules/open/vendor/xdg-open: Permission denied
 Use --force to continue.
pls suggest

**Comment by kelvin4incubit** [comment]
use grunt server --force
