### ISSUE TITLE
count on index is buggy

### ISSUE THREAD

**Issue by delbertooo** [axemclion/IndexedDBShim#74]
This can never work:

```
IDBIndex.prototype.__fetchIndexData = function(key, opType){
    // [...]
    if (typeof opType === "count") {
    // [...]
}
```

The `typeof` in the condition is just wrong, it should be:

```
if (opType === "count") { /* [...] */ }
```

**Comment by axemclion** [comment]
Nice find. 

@delbertooo Can you send in a pull request for this please ? Send it to the 'incoming-pr' branch.
