### ISSUE TITLE
TypeError: Result of expression 'db' [null] is not an object. at IndexedDBShim.js:1516

### ISSUE THREAD

**Issue by guofengzh** [axemclion/IndexedDBShim#77]
I have Samsung I589, which run Android 2.2.3. I deployed your demo  "IndexedDB Example on Cordova (Phonegap) - Android" from http://blog.nparashuram.com/2012/10/indexeddb-example-on-cordova-phonegap_12.html. It works well.

I developed an App using IndexedDBShim and Jquery-IndexedDB, the latest dist on github, and Cordova 2.9.0. When I deployed it on this mobile, I got:
09-01 23:58:24.295: E/Web Console(2257): TypeError: Result of expression 'db' [null] is not an object. at file:///android_asset/www/js/libs/indexeddb/IndexedDBShim.js:1516

I have another mobile, which runs Android 4.2.2. When I deploy this app to this mobile, the App runs well.

How to fix the issue?

Your help is appreciated.

Guofeng

**Comment by mcfarljw** [comment]
I tried loading that example on Android 2.3.6, 4.1.2 and 4.2.2. The app loaded alright, but none of the data seemed to load. So you were able to get it to load with all of the data just like the pictures show? Did you test it outside of the emulator?

To be more specific. I get the following error when loading it on my device with 4.1.2 from Eclipse:

```
09-02 19:08:54.041: D/CordovaLog(14947): Uncaught TypeError: Illegal constructor
09-02 19:08:54.041: D/CordovaLog(14947): file:///android_asset/www/jquery.indexeddb.js: Line 286 : Uncaught TypeError: Illegal constructor
09-02 19:08:54.041: E/Web Console(14947): Uncaught TypeError: Illegal constructor:286
```

When I update to latest version of the shim and jquery wrapper I get these errors:

```
09-02 19:19:50.596: E/Web Console(15256): Uncaught TypeError: Cannot assign to read only property 'PREV' of function IDBCursor() { [native code] }:6
09-02 19:19:52.696: D/CordovaLog(15256): Uncaught TypeError: Object function (a,b){return new e.fn.init(a,b,h)} has no method 'indexedDB'
09-02 19:19:52.696: D/CordovaLog(15256): file:///android_asset/www/index.html: Line 111 : Uncaught TypeError: Object function (a,b){return new e.fn.init(a,b,h)} has no method 'indexedDB'
09-02 19:19:52.696: E/Web Console(15256): Uncaught TypeError: Object function (a,b){return new e.fn.init(a,b,h)} has no method 'indexedDB':111
```

**Comment by guofengzh** [comment]
Here is a solution for it:
http://rashidnoorani.blogspot.com/2011/06/how-to-run-html-5-app-from-android.html
so I have to modify org.apache.cordova.CordovaChromeClient.onExceededDatabaseQuota() to solve it.
Now my app works on Android 2.2.3, my older mobile phone.

@mcfarljw 
I test that demo on my mobile phone, not on emulator.
I do not change any artifact in that demo. For it to work, I just install sdk 15 for environment (I used 17 before).

All test data loaded, and I could add/move items to card and wishlist, or clear them. 

for me, it woks well on Adroid 4.2.2 too.

**Comment by mcfarljw** [comment]
Hmm, very strange. I didn't modify any of the files either. I suppose I look into mine a bit more and then open another issue if it still doesn't work. Thanks!
