### ISSUE TITLE
Updating using a cursor fails on Safari / IOS6 

### ISSUE THREAD

**Issue by damienthiery** [axemclion/IndexedDBShim#78]
The test 19 "Cursor : Updating using a cursor" does not pass, it never ends ....

**Comment by Toneti777** [comment]
Yes I have the same problem...
And my application dosen't work well on Safari or Chrome for Ipad.

**Comment by DickvdBrink** [comment]
I think I fixed this issue, see #99

**Comment by DickvdBrink** [comment]
Fixed in latest version
