### ISSUE TITLE
License

### ISSUE THREAD

**Issue by niclashoyer** [axemclion/IndexedDBShim#84]
I had troubles finding the license for the project. Is the information for "Apache 2.0" correct in package.json? Maybe a LICENSE file or a note in the README would be helpful.

**Comment by DickvdBrink** [comment]
I think it is correct, http://nparashuram.com/IndexedDBShim/ also says it is apache 2.0 (right under the "source" section)

**Comment by vstirbu** [comment]
+1 for having the license explicitly in the repository

**Comment by DickvdBrink** [comment]
Fixed, thanks for creating a issue for it :)
