### ISSUE TITLE
Firefox 24: setting a property that only has a getter

### ISSUE THREAD

**Issue by desau** [axemclion/IndexedDBShim#85]
When loading the shim into Firefox 24 (I know -- it's not needed .. but I don't have selective inclusion for only Safari yet), I see this error:

An error has occurred on line 2 of indexeddb.shim.js
TypeError: setting a property that has only a getter

**Comment by jough** [comment]
Same error with the non-minified Shim on Line 1653 in Firefox 25.0.1 / Mac

**Comment by DickvdBrink** [comment]
Thanks for the report! It is fixed in 3b66b42
