### ISSUE TITLE
Opening cursors on Indexes (v0.1.2)

### ISSUE THREAD

**Issue by theycallmezip** [axemclion/IndexedDBShim#90]
It appears as if it's not possible to open a cursor on an index in Safari or Chrome on the iOS (The issue appears to also be present in desktop Safari).

Specifically, if I am to open a cursor on an open database (named db) on a given store (storename) with the following code:
"db.transaction(storename, 'readonly').objectStore(storename).openCursor()"
Everything is fine, the cursor opens and I am able to cycle through the store's contents.

However, if I want to open a cursor on an index for the property 'name' using the following code,
"var test = db.transaction(storename, 'readonly').objectStore(storename).index('name').openCursor();"
the object test will remain in the  status 'pending' for eternity and never run the thread.  This is a significant problem for me, as I would prefer to allow the DB to handle some of the sorting.

I am using v0.1.2 - 2013-07-11

**Comment by matb33** [comment]
I'm experiencing the exact same issue (have just encountered this under iOS)

**Comment by matb33** [comment]
If it helps at all, while trying to debug this I noticed that in the database my indexes were always "5-undefined".
